# -*- coding: utf-8 -*-
"""Brain tumor segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8KXnXAXyir9DQbxFxDDJcR03hgD9RZF
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image

image_org = Image.open('/content/2993.png')

plt.imshow(image_org)
plt.title('Original Image')
plt.axis('off')
plt.show()

image_np = np.array(image_org)
image_np.shape

pixels = image_np.reshape(-1, 4)

pixels_df = pd.DataFrame (pixels, columns=['R', 'G', 'B', 'A'])
pixels_df

from sklearn.cluster import KMeans

clf = KMeans(n_clusters=3, n_init='auto')
clf.fit(pixels)

pd.DataFrame(clf.cluster_centers_, columns=['R', 'G', 'B', 'A'])

pixels_df['label'] = clf.labels_
pixels_df

pixels_seg0 = clf.cluster_centers_[clf.labels_]
pd.DataFrame(pixels_seg0, columns=['R', 'G', 'B', 'A'])

pixels_seg = np.clip(pixels_seg0.astype('uint8'), 0, 255)
pd.DataFrame(pixels_seg, columns=['R', 'G', 'B', 'A'])

image_seg = pixels_seg.reshape(image_np.shape)

plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(image_org)
plt.title('Original picture')
plt.axis('off')

plt.subplot(1, 2, 2)
plt.imshow(image_seg)
plt.title('Segmented Picture')
plt.axis('off')

plt.show()